server:
  port: 8085
spring.cloud.stream:
  kafka.streams.binder:
    brokers: localhost:9092
    application-id: address_generate
    configuration:
      commit.interval.ms: 1000
  bindings:
    address-in-0:
      destination: bank_account
      consumer:
        useNativeEncoding: false
    address-out-0:
      destination: address
      producer:
        useNativeEncoding: false

address:
  generator:
    address: https://randomapi.com/api/hdh1qlye?key=1FK1-1UB8-FCVP-MBRA&noinfo&sole

logging.level.com.mfirsov: DEBUG